services:
  db:
    image: postgres:15-alpine
    container_name: moviemanager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MovieManager
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: moviemanager-frontend
    ports:
      - "3001:80"
    depends_on:
      - db
    restart: unless-stopped


volumes:
  pgdata:
